name: build & test (Ubuntu 24.04)

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/src/**') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential make cmake ccache pkg-config git wget curl \
            libeigen3-dev libpng-dev libjpeg-dev libtiff-dev \
            libwebp-dev libopenjp2-7-dev zlib1g-dev liblzma-dev \
            libfreetype6-dev libxml2-dev \

      - name: Install Magick 7 library
        run: |
          cd $HOME
          git clone --depth 1 --branch main https://github.com/ImageMagick/ImageMagick.git ImageMagick-7.1.2
          cd ImageMagick-7.1.2
          # Configure and Build
          ./configure
          make
          # Install
          sudo make install
          # Configure the dynamic linker run-time bindings
          sudo ldconfig /usr/local/lib
          # Check if magick is installed
          pkg-config --list-all | grep -i magick

      - name: Install argparse
        run: |
          cd $HOME
          git clone https://github.com/p-ranav/argparse
          cd argparse
          mkdir build
          cd build
          cmake -DARGPARSE_BUILD_SAMPLES=on -DARGPARSE_BUILD_TESTS=on ..
          make
          # Install the library
          sudo make install

      - name: Clean previous build
        run: |
          if [ -d build ]; then
          echo "Removing stale build directory"
          rm -rf build
          fi

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_INSTALL_PREFIX=./

      - name: Build
        run: cmake --build build

      - name: Install into workspace (local install)
        run: cmake --install build --verbose

      - name: Run tests
        run: |
          set -o pipefail
          ctest --test-dir build --output-on-failure | tee test_output.txt
          if ! grep -q "100% tests passed" test_output.txt; then
            echo "Some tests failed (see test_output.txt)."
            exit 1
          fi

      - name: Upload build artifact (binary)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: astar_search-binary
          path: |
            build/astar_search
            build/src/astar_search/astar_search
          retention-days: 5

      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: ./test_output.txt
          retention-days: 5

      - name: Show build summary
        if: always()
        run: |
          echo "Build finished. Contents of build/:"
          ls -al build || true
          echo "Installed CMake cache:"
          sed -n '1,200p' build/CMakeCache.txt || true
